### ISSUE TITLE
Crashes on level start [Windows]

### ISSUE THREAD

**Issue by xpac1985** [git-learning-game/oh-my-git#27]
I just downloaded this to my work laptop, which is running Windows 10 20H2.
On the first start it threw an error that seems to be related to the `C:\Users\username\AppData\Roaming\Oh My Git` directory - deleting it will trigger the error once more. However, the directory is successfully created, including a `savegame.json` and a `tmp` subdirectory.

![image](https://user-images.githubusercontent.com/6882771/108981064-a3c49300-768c-11eb-9d7a-18e458048319.png)

I just mention this if it is somehow related to my actual issue.

Now - the game is running. I select `Levels` -> `Living dangerously`... it hangs for a few seconds, make a "success" sound and then just closes. You can see this in the command line:

![image](https://user-images.githubusercontent.com/6882771/108981448-06b62a00-768d-11eb-933e-748cf78ab599.png)

What is noteworthy is that in the error message that i partially pixelated, it says:
`Refusing to delete directory C: /Users/username/AppData/Roaming/Oh my that does not start with C: /Users/USERNAME/AppData/Roaming/Oh my Git/tmp/`
Note that the first occurence of `username` is in small letters, while the second one is in capital letters. I assume this is a Windows nuisance (because on Windows these paths are the same), so if you do any path comparison, I guess lowercasing both paths on Windows might already solve that problem.
The actual folder is displayed by Windows to be completely lowercase, however the environment variable %USERNAME% has my username in all caps.

Oh, and on the next start of the game, the first level has a golden marker as if I had gotten some achievement.

Summary:
- Error message that doesn't seem to cause any real issue on screenshot #1 
- Error messages that seem to be core of the problem in screenshot #2, likely related to lowercase/uppercase paths
- Got achievement also the game crashed while loading the level.

Thanks for your work though :)

**Comment by xpac1985** [comment]
Found a temporary workaround.
- Open CLI with `cmd`
- Type `echo %USERNAME%`, see your username is in capital letters
- Do `set username=myusername` to change the environment variable to the lowercase version of your username
- Verify with `echo %USERNAME%` again
- Using that same shell window, navigate to whereever oh-my-git.exe is located, start it from there
- Profit!
So yeah, seems the uppercase username in the environment var causes the issue, maybe because this is a domain joined computer...

**Comment by blinry** [comment]
Ha, thanks for the detailed bug report! Yeah, I agree, comparing those two strings case-insensitively would likely help! This triggered a problem in one part of our code which is extra-careful not to delete the wrong things. :)

**Comment by itsuki-n22** [comment]
I also just downloaded this to my work laptop, which is running Windows 10.
But when I click oh-my-git.exe, it crashes.
Here is error messages when I run on cmd.


![error](https://user-images.githubusercontent.com/54315732/110051942-0e1ab900-7d9a-11eb-8a16-814f189cac6e.png)

**Comment by blinry** [comment]
@itsuki-n22 This was a timing-related problem in how we emulate a UNIX environment on Windows, and I think I fixed that to be more stable in version 0.6.2. Can you try again and report back? :)

**Comment by TuncJH** [comment]
The game closes for me too, when I choose a level. Running version 0.6.2, on Windows 10

**Comment by clayms** [comment]
Same work-around as @xpac1985 except in PowerShell:

1. Go to folder where `oh-my-git.exe` is located
1. start PowerShell in that folder by doing one of the following:
   1.  <kbd>shift</kbd> + right-click in folder for context menu, select `Open PowerShell window here`
   1. or type `powershell` in folder location bar.
1. run the following 

```
 echo $env:username
$env:username="your.user.name"
.\oh-my-git.exe
```

**Comment by clayms** [comment]
Though it does work using the work-around above, the following errors appear on exit.

```powershell
PS C:\Program Files (x86)\ohMyGit> echo $env:username
Your.User.Name
PS C:\Program Files (x86)\ohMyGit> $env:username="your.user.name"
PS C:\Program Files (x86)\ohMyGit> echo $env:username
your.user.name
PS C:\Program Files (x86)\ohMyGit>
PS C:\Program Files (x86)\ohMyGit> .\oh-my-git.exe
Godot Engine v3.2.3.stable.official - https://godotengine.org
OpenGL ES 3.0 Renderer: Intel(R) HD Graphics 520
WARNING: init_render_device: WASAPI: Unsupported number of channels: 1
     At: drivers/wasapi/audio_driver_wasapi.cpp:330

connected!
WARNING: thread_func: WASAPI: Current device invalidated, closing device
     At: drivers/wasapi/audio_driver_wasapi.cpp:650
WARNING: init_render_device: WASAPI: Unsupported number of channels: 1
     At: drivers/wasapi/audio_driver_wasapi.cpp:330
WARNING: thread_func: WASAPI: Current device invalidated, closing device
     At: drivers/wasapi/audio_driver_wasapi.cpp:650
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112
WARNING: cleanup: ObjectDB instances leaked at exit (run with --verbose for details).
     At: core/object.cpp:2135
ERROR: clear: Resources still in use at exit (run with --verbose for details).
   At: core/resource.cpp:477
ERROR: There are still MemoryPool allocs in use at exit!
   At: core/pool_vector.cpp:69

```

**Comment by TuncJH** [comment]
Sorry, I'm new at this, I don't get it.. Do you change your username to be all lowercase? Or do you change it to literally "your.user.name"? I tried both with Powershell, and it still crashes.

Godot Engine v3.2.3.stable.official - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce GTX 1660 SUPER/PCIe/SSE2

connected!
ERROR: call: Refusing to delete directory C:/Users/tunct/AppData/Roaming/Oh My Git/tmp/repos/yours/ that does not start with C:/Users/your.user.name/AppData/Roaming/Oh My Git/tmp/
   At: modules/gdscript/gdscript_functions.cpp:803
FATAL ERROR: Refusing to delete directory C:/Users/tunct/AppData/Roaming/Oh My Git/tmp/repos/yours/ that does not start with C:/Users/your.user.name/AppData/Roaming/Oh My Git/tmp/
SCRIPT ERROR: crash: Invalid call. Nonexistent function 'fatal_error' in base 'SceneTree'.
          At: res://scenes/helpers.gdc:12
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112
WARNING: cleanup: ObjectDB instances leaked at exit (run with --verbose for details).
     At: core/object.cpp:2135
ERROR: clear: Resources still in use at exit (run with --verbose for details).
   At: core/resource.cpp:477
ERROR: There are still MemoryPool allocs in use at exit!
   At: core/pool_vector.cpp:69
PS G:\itch_games\games\oh-my-git>

**Comment by clayms** [comment]
@TuncJH  
> Do you change your username to be all lowercase?    

Yes.

> Or do you change it to literally "your.user.name"? 

No.

> I tried both with Powershell, and it still crashes when I select a level.  

Did you start `.\oh-my-git.exe` from the same PowerShell session that you changed your user name in?  
Did you `echo $env:username` to see if your Windows user name is all lowercase?  

Other than that, I don't know. ¯\_(ツ)_/¯

**Comment by blinry** [comment]
Attempted a fix for the username case-sensitivity thing! This is something the game should handle. Please confirm once version 0.6.3 is on itch later today, everyone!

**Comment by TuncJH** [comment]
I tried version 0.6.3, still crashes when loading a level or going to sandbox. The lowercase username fix in Powershell didn't help me, so I probably have a different issue.
